version: "3.1"
services: 
  rabbitmq:
    image: rabbitmq:3.8.11-management-alpine
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:15672
      - 15672:15672
    volumes:
      - /var/lib/rabbitmq:/var/lib/rabbitmq