version: "3.1"
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    restart: always
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment: 
      - discovery.type=single-node
  kibana:
    image: kibana:7.4.2
    restart: always
    container_name: kibana
    ports: 
      - 5601:5601
    environment: 
      - elasticsearch_url=http://192.168.5.51:9200
    depends_on: 
      - elasticsearch    