version: "3.1"
services:
  nginx:
    image: nginx:1.19.6
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes: 
      - /opt/docker_compose_test/nginx/conf.d:/etc/nginx/conf.d
      - /usr/share/nginx/html:/usr/share/nginx/html